# Generated by Django 3.2 on 2021-05-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='unique_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('POS', 'Postive'), ('NUE', 'Negative'), ('NEG', 'Neutral')], max_length=3),
        ),
    ]
