# Generated by Django 3.2 on 2021-05-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetes_app', '0002_auto_20210521_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='sentiment',
            field=models.CharField(choices=[('POS', 'Postive'), ('NUE', 'Negative'), ('NEG', 'Neutral')], max_length=3),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='unique_id',
            field=models.TextField(),
        ),
    ]
