# Generated by Django 3.2 on 2021-05-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetes_app', '0003_auto_20210521_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('POS', 'Postive'), ('NUE', 'Negative'), ('NEG', 'Neutral')], max_length=3),
        ),
    ]
